# Generated by Django 5.2.5 on 2025-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['completed', 'order_field']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
