# Generated by Django 5.2.5 on 2025-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['order_field']},
        ),
        migrations.AddField(
            model_name='todo',
            name='order_field',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
