# Generated by Django 5.2.5 on 2025-08-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_todo_options_remove_todo_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
