# Generated by Django 5.2.5 on 2025-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order_field',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
