# Generated by Django 5.2.5 on 2025-08-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_tasks_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
    ]
